#!/bin/sh

tmpfile="$(mktemp)"
use_height=""
hayden_directory=""
script_location=$(CDPATH="" cd -- "$(dirname -- "$0")" && pwd -P)
while :; do
	case "$1" in
	"--help")
		cat << EOF
Haydenfetch is a CLI system information tool in POSIX sh. It calls neofetch (which needs bash) with an image of hayden.

OPTIONS:
i, -i, img, --img, w3m, --w3m	Use the w3m image backend for neofetch
-h, --height <height>		Display hayden image of height <height>
--haydendir <directory>		Make haydenfetch search for haydens in <directory>
EOF
	exit 0
	;;
	"--w3m" | "w3m" | "--img" | "img" | "-i" | "i")
		[ "$DEBUG" = "true" ] && echo "Using w3m image backend for neofetch"
		use_w3m="true"
		;;
	"--height" | "-h")
		if [ "$use_height" = "" ]; then
			use_height="$2"
			[ "$DEBUG" = "true" ] && echo "Using height $height"
		else
			echo "You can only specify the height argument once!"
		fi
		;;
	"--haydendir")
		hayden_directory="$2"
		shift
		;;
	*)
		if [ -z "$1" ]; then
			break
		fi
		#            echo "Could not interpret parameter '$1'."
		;;
	esac
	shift
done

# search for haydens
if [ "$hayden_directory" != "" ]; then
	true
elif [ -d "./haydens" ]; then
	hayden_directory="$(pwd)/haydens"
elif [ -d "$script_location/haydens" ]; then
	hayden_directory="$script_location/haydens"
elif [ -d "$script_location/../share/haydenfetch/haydens" ]; then
	hayden_directory="$script_location/../share/haydenfetch/haydens"
fi
[ "$DEBUG" = "true" ] && echo "Found hayden directory in $hayden_directory."
if [ "$hayden_directory" = "" ]; then
	echo "error: no hayden directory found. Try passing --haydendir <directory>."
	exit 1
fi
selected_hayden=$(find "$hayden_directory" -name "*.jpg" | shuf -n 1)
[ "$DEBUG" = "true" ] && echo "Selected Hayden image at $selected_hayden."
if [ "$selected_hayden" = "" ]; then
	echo "error: no haydens found in $hayden_directory"
	exit 2
fi
if [ "$use_height" != "" ]; then
	height="$use_height"
else
	height="$(($(stty size | awk '{print $1}') - 5))"
fi
# execute neofetch
# shebang is not respected on some jailbreaks
# we use -c option because there might be a file named 'neofetch' in .
if [ "$LC_TERMINAL" = "iTerm2" ]; then
	bash -c 'neofetch --iterm2 '"$selected_hayden"
elif [ "$use_w3m" = "true" ]; then
	bash -c 'neofetch --w3m '"$selected_hayden"
else
	jp2a --height="$height" "$selected_hayden" >"$tmpfile"
	bash -c 'neofetch --source '"$tmpfile"
fi

rm "$tmpfile"
